name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  project_id:
    required: true
    description: 'The ID of your project'
runs:
  using: 'node16'
  main: 'dist/index.js'
